/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX ""
#define TARGET_ARCH "i386"
#define TARGET_I386 1
#define CONFIG_SOFTMMU 1
#define CONFIG_DM 1
#define CONFIG_STUBDOM 1
#define NO_UNIX_SOCKETS 1
#define NO_DAEMONIZE 1
#define NO_AIO 1
